FROM apache/airflow:2.10.5

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

COPY --chown=airflow:root requirements-airflow.txt /tmp/requirements-airflow.txt

USER airflow

RUN pip install --no-cache-dir 'apache-airflow==2.10.5' -r /tmp/requirements-airflow.txt \
    && rm -rf /tmp/requirements-airflow.txt ~/.cache/pip

CMD ["airflow", "standalone"]
